name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven

      # Aquí configuramos Maven para que use las credenciales de GitHub
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ secrets.USERNAME }}</username><password>${{ secrets.TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile project
        run: mvn clean package

      # Configurar Docker Hub para autenticar
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        if: success()
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir la imagen de Docker
      - name: Build Docker image
        if: success()
        run: docker build -t mariafernanda2798/qr:latest .

      # Subir la imagen a Docker Hub
      - name: Push Docker image
        if: success()
        run: docker push mariafernanda2798/qr:latest
  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Configurar Azure para autenticar
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Desplegar el contenedor en Azure App Service
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v2
        if: success()
        with:
          app-name: "qr-ms"
          images: "mariafernanda2798/qr:latest"